boot.o: boot.S multiboot.h x86_desc.h types.h
interrupt_handlers.o: interrupt_handlers.S interrupt_handlers.h
x86_desc.o: x86_desc.S x86_desc.h types.h
fs.o: fs.c lib.h types.h fs.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h lib.h types.h x86_desc.h interrupt_handlers.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h page.h keyboard.h rtc.h terminal.h fs.h
keyboard.o: keyboard.c keyboard.h types.h lib.h i8259.h terminal.h
lib.o: lib.c lib.h types.h
page.o: page.c page.h types.h
rtc.o: rtc.c rtc.h types.h lib.h i8259.h
terminal.o: terminal.c terminal.h lib.h types.h keyboard.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h i8259.h keyboard.h \
  rtc.h fs.h terminal.h
