boot.o: boot.S multiboot.h x86_desc.h types.h
interrupt_handlers.o: interrupt_handlers.S interrupt_handlers.h
system_call_handler.o: system_call_handler.S
x86_desc.o: x86_desc.S x86_desc.h types.h
fs.o: fs.c lib.h types.h terminal.h fs.h system_execute_c.h page.h \
  x86_desc.h
i8259.o: i8259.c i8259.h types.h lib.h terminal.h
idt.o: idt.c idt.h lib.h types.h terminal.h x86_desc.h \
  interrupt_handlers.h system_execute_c.h fs.h page.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h terminal.h \
  i8259.h debug.h tests.h system_execute_c.h fs.h page.h idt.h keyboard.h \
  rtc.h pit.h scheduler.h
keyboard.o: keyboard.c keyboard.h terminal.h types.h lib.h i8259.h
lib.o: lib.c lib.h types.h terminal.h
page.o: page.c page.h types.h
pit.o: pit.c pit.h i8259.h types.h lib.h terminal.h scheduler.h
rtc.o: rtc.c rtc.h types.h lib.h terminal.h i8259.h
scheduler.o: scheduler.c scheduler.h terminal.h types.h page.h \
  system_execute_c.h fs.h lib.h x86_desc.h
system_execute_c.o: system_execute_c.c system_execute_c.h fs.h types.h \
  lib.h terminal.h page.h x86_desc.h rtc.h i8259.h idt.h scheduler.h
terminal.o: terminal.c terminal.h types.h keyboard.h lib.h page.h rtc.h \
  i8259.h system_execute_c.h fs.h x86_desc.h scheduler.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h terminal.h i8259.h \
  keyboard.h rtc.h fs.h system_execute_c.h page.h
